/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;

/**
 *
 * @author Iqbal-Asi
 */
public class Create_Employee_Account extends javax.swing.JInternalFrame {
	ConnectClass c;
	Validation v;

	/**
	 * Creates new form Create_Employee_Account
	 */
	public Create_Employee_Account() {
		getContentPane().setBackground(new Color(128, 255, 255));
		getContentPane().setForeground(new Color(128, 255, 255));
		initComponents();

		c = new ConnectClass();
		v = new Validation();
		setTitle("New Student");
		getID();
		statusCombo();

	}
	public void getID() {
		try {
			ResultSet rs = c.st.executeQuery("select max(std_id) from tbl_std ");
			if (rs.next()) {
				int stdID = Integer.parseInt(rs.getString(1)) + 1;
				textEmp_ID.setText(String.valueOf(stdID));
			}

		} catch (Exception ex) {
			System.out.println(ex.toString());
		}
	}

	/**
	 * Get Date Method
	 */
	

	/**
	 * Filling Batch
	 */
	
	public void statusCombo() {
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		Employee_ID = new javax.swing.JLabel();
		Emp_Name = new javax.swing.JLabel();
		Position = new javax.swing.JLabel();
		Username = new javax.swing.JLabel();
		Passwword = new javax.swing.JLabel();
		textEmp_ID = new javax.swing.JLabel();
		textEmp_Name = new javax.swing.JTextField();

		setMaximumSize(new java.awt.Dimension(990, 550));
		setMinimumSize(new java.awt.Dimension(990, 550));
		setPreferredSize(new java.awt.Dimension(990, 550));
		getContentPane().setLayout(null);

		Employee_ID.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		Employee_ID.setForeground(new Color(0, 0, 0));
		Employee_ID.setText("Employee ID :");
		getContentPane().add(Employee_ID);
		Employee_ID.setBounds(80, 28, 110, 30);

		Emp_Name.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		Emp_Name.setForeground(new Color(0, 0, 0));
		Emp_Name.setText("Employee Name :");
		getContentPane().add(Emp_Name);
		Emp_Name.setBounds(80, 69, 110, 30);

		Position.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		Position.setForeground(new Color(0, 0, 0));
		Position.setText("Position :");
		getContentPane().add(Position);
		Position.setBounds(80, 110, 110, 30);

		Username.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		Username.setForeground(new Color(0, 0, 0));
		Username.setText("Username :");
		getContentPane().add(Username);
		Username.setBounds(80, 151, 109, 30);

		Passwword.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		Passwword.setForeground(new Color(0, 0, 0));
		Passwword.setText("Password :");
		getContentPane().add(Passwword);
		Passwword.setBounds(80, 192, 109, 30);

		textEmp_ID.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
		textEmp_ID.setForeground(new java.awt.Color(255, 255, 255));
		getContentPane().add(textEmp_ID);
		textEmp_ID.setBounds(221, 28, 180, 30);

		textEmp_Name.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
	
		getContentPane().add(textEmp_Name);
		textEmp_Name.setBounds(221, 69, 180, 30);
		scrollPane.setBounds(80, 276, 729, 201);
		getContentPane().add(scrollPane);
		
		tableEmployee = new JTable();
		tableEmployee.setModel(new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
			}
		));
		scrollPane.setViewportView(tableEmployee);
		
		textPosition = new JTextField();
		textPosition.setFont(new Font("Calibri", Font.BOLD, 14));
		textPosition.setBounds(221, 113, 180, 30);
		getContentPane().add(textPosition);
		
		textUsername = new JTextField();
		textUsername.setFont(new Font("Calibri", Font.BOLD, 14));
		textUsername.setBounds(221, 151, 180, 30);
		getContentPane().add(textUsername);
		
		textPassword = new JTextField();
		textPassword.setFont(new Font("Calibri", Font.BOLD, 14));
		textPassword.setBounds(221, 192, 180, 30);
		getContentPane().add(textPassword);
		
		Email = new JLabel();
		Email.setText("Email");
		Email.setForeground(Color.BLACK);
		Email.setFont(new Font("Candara", Font.BOLD, 14));
		Email.setBounds(80, 233, 109, 30);
		getContentPane().add(Email);
		
		textEmail = new JTextField();
		textEmail.setFont(new Font("Calibri", Font.BOLD, 14));
		textEmail.setBounds(221, 235, 180, 30);
		getContentPane().add(textEmail);
		
		btnNewButton = new JButton("");
		btnNewButton.setIcon(new ImageIcon(Create_Employee_Account.class.getResource("/create_icon.png")));
		btnNewButton.setBounds(533, 235, 124, 30);
		getContentPane().add(btnNewButton);;

		setBounds(0, 0, 990, 550);
	}// </editor-fold>//GEN-END:initComponents

	private javax.swing.JLabel Employee_ID;
	private javax.swing.JLabel Passwword;
	private javax.swing.JLabel textEmp_ID;
	private javax.swing.JLabel Emp_Name;
	private javax.swing.JLabel Position;
	private javax.swing.JLabel Username;
	private javax.swing.JTextField textEmp_Name;
	private final JScrollPane scrollPane = new JScrollPane();
	private JTable tableEmployee;
	private JTextField textPosition;
	private JTextField textUsername;
	private JTextField textPassword;
	private JLabel Email;
	private JTextField textEmail;
	private JButton btnNewButton;
}
